---
# tasks file for prod
- name: install tomcat8
  become: 'yes'
  apt:
    name: tomcat8
    state: present
- name: pull artifact
  become: 'yes'
  synchronize:
    src: '{{ artifact_folder }}/app.war'
    dest: '{{ tomcat_webapps_folder }}/app.war'
    compress: 'yes'
  notify: restart tomcat
