---
- name: build-server configuration
  hosts: build
  become: 'yes'
  roles:
    - common
    - build

- name: prod-server configuration
  hosts: prod
  become: 'yes'
  roles:
    - common
    - prod
